# [theme]
# base="dark"
# # primaryColor="purple"
# # backgroundColor="#363457"
# # secondaryBackgroundColor="#F0F2F6"
# # textColor="#FFFFFF"
# font="serif"


# [theme]
# primaryColor="#202835"
# backgroundColor="#cad2df"
# secondaryBackgroundColor="#ecdff6"
# textColor="#020100"
# font="serif"

# [theme]
# primaryColor="#dad4d1"
# backgroundColor="#2e2725"
# secondaryBackgroundColor="#090808"
# textColor="#d3cae8"
# font="serif"

#newone
# [theme]
# primaryColor="#22204c"
# backgroundColor="#b4b3df"
# secondaryBackgroundColor="#d5e3f9"
# textColor="#281731"
# font="serif"

# [theme]
# primaryColor="#282929"
# backgroundColor="#d6d6d7"
# secondaryBackgroundColor="#ffffff"
# textColor="#051a07"
# font="serif"

#dark
# [theme]
# primaryColor="#fcfdfd"
# backgroundColor="#020203"
# secondaryBackgroundColor="#000100"
# textColor="#dfeef3"

#light
[theme]
primaryColor="#282929"
backgroundColor="#d6d6d7"
secondaryBackgroundColor="#ffffff"
textColor="#051a07"
font="serif"


# [theme]
# primaryColor="#0d0c08"
# backgroundColor="#f7f6f2"
# secondaryBackgroundColor="#e3c3c6"
# textColor="#0c0b0f"
# font="serif"

# [theme]
# primaryColor="#0a0a0a"
# backgroundColor="#f5f5f5"
# secondaryBackgroundColor="#e9eae8"
# textColor="#5a463e"
# font="serif"